<script>
    function add() {
        a = 10;
        b = 20;
        console.log(a+z);
    } 
    try {
        console.log("Task Started...");
        add();
    }
    catch(e) {
        console.log("Some error occured and handle..!");
    }
    finally {
        console.log("Task is ended...!");
    }
    console.log("Task 1");
    console.log("Task 2");
</script>

<!--script>

    function add(){

        a=10;

        b=20;

        console.log(a+z);

    }

    try{

        console.log('Task Started..!!')

        add();

    }

    catch(e){

        console.log('Some Error Occurred and Handled..!!');

    }

    finally{

        console.log('Task Ended..!!')

    }

    console.log('Next Task 1');

    console.log('Next Task 2');

</script-->